[*] ending @ 15:21:36 /2025-03-08/

sergio@Sergio:~$ http://localhost:4000/api/transfer.
-bash: http://localhost:4000/api/transfer.: No such file or directory
sergio@Sergio:~$ sqlmap -u "http://localhost:4000/api/transfer?id=123" --risk=3 --level=5
        ___
       __H__
 ___ ___[']_____ ___ ___  {1.6.4#stable}
|_ -| . [,]     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V...       |_|   https://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 15:21:45 /2025-03-08/

[15:21:45] [INFO] testing connection to the target URL
[15:21:45] [INFO] testing if the target URL content is stable
[15:21:46] [WARNING] target URL content is not stable (i.e. content differs). sqlmap will base the page comparison on a sequence matcher. If no dynamic nor injectable parameters are detected, or in case of junk results, refer to user's manual paragraph 'Page comparison'
how do you want to proceed? [(C)ontinue/(s)tring/(r)egex/(q)uit] c
[15:21:49] [INFO] searching for dynamic content
[15:21:49] [INFO] dynamic content marked for removal (6 regions)
[15:21:49] [INFO] testing if GET parameter 'id' is dynamic
[15:21:49] [WARNING] GET parameter 'id' does not appear to be dynamic
[15:21:49] [WARNING] heuristic (basic) test shows that GET parameter 'id' might not be injectable
[15:21:49] [INFO] testing for SQL injection on GET parameter 'id'
[15:21:49] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause'
[15:21:50] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause'
[15:21:50] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause (NOT)'
[15:21:51] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause (subquery - comment)'
[15:21:52] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause (subquery - comment)'
[15:21:52] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause (comment)'
[15:21:52] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause (comment)'
[15:21:52] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause (NOT - comment)'
[15:21:52] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause (MySQL comment)'
[15:21:52] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause (MySQL comment)'
[15:21:53] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause (NOT - MySQL comment)'
[15:21:53] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause (Microsoft Access comment)'
[15:21:53] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause (Microsoft Access comment)'
[15:21:53] [INFO] testing 'MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause'
[15:21:54] [INFO] testing 'MySQL AND boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (MAKE_SET)'
[15:21:54] [INFO] testing 'MySQL OR boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (MAKE_SET)'
[15:21:54] [INFO] testing 'MySQL AND boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (ELT)'
[15:21:55] [INFO] testing 'MySQL OR boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (ELT)'
[15:21:55] [INFO] testing 'MySQL AND boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (bool*int)'
[15:21:56] [INFO] testing 'MySQL OR boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (bool*int)'
[15:21:56] [INFO] testing 'PostgreSQL AND boolean-based blind - WHERE or HAVING clause (CAST)'
[15:21:56] [INFO] testing 'PostgreSQL OR boolean-based blind - WHERE or HAVING clause (CAST)'
[15:21:57] [INFO] testing 'Oracle AND boolean-based blind - WHERE or HAVING clause (CTXSYS.DRITHSX.SN)'
[15:21:57] [INFO] testing 'Oracle OR boolean-based blind - WHERE or HAVING clause (CTXSYS.DRITHSX.SN)'
[15:21:57] [INFO] testing 'Boolean-based blind - Parameter replace (original value)'
[15:21:57] [INFO] testing 'MySQL boolean-based blind - Parameter replace (MAKE_SET)'
[15:21:57] [INFO] testing 'MySQL boolean-based blind - Parameter replace (MAKE_SET - original value)'
[15:21:57] [INFO] testing 'MySQL boolean-based blind - Parameter replace (ELT)'
[15:21:57] [INFO] testing 'MySQL boolean-based blind - Parameter replace (ELT - original value)'
[15:21:57] [INFO] testing 'MySQL boolean-based blind - Parameter replace (bool*int)'
[15:21:57] [INFO] testing 'MySQL boolean-based blind - Parameter replace (bool*int - original value)'
[15:21:57] [INFO] testing 'PostgreSQL boolean-based blind - Parameter replace'
[15:21:57] [INFO] testing 'PostgreSQL boolean-based blind - Parameter replace (original value)'
[15:21:57] [INFO] testing 'PostgreSQL boolean-based blind - Parameter replace (GENERATE_SERIES)'
[15:21:57] [INFO] testing 'PostgreSQL boolean-based blind - Parameter replace (GENERATE_SERIES - original value)'
[15:21:57] [INFO] testing 'Microsoft SQL Server/Sybase boolean-based blind - Parameter replace'
[15:21:57] [INFO] testing 'Microsoft SQL Server/Sybase boolean-based blind - Parameter replace (original value)'
[15:21:57] [INFO] testing 'Oracle boolean-based blind - Parameter replace'
[15:21:57] [INFO] testing 'Oracle boolean-based blind - Parameter replace (original value)'
[15:21:57] [INFO] testing 'Informix boolean-based blind - Parameter replace'
[15:21:57] [INFO] testing 'Informix boolean-based blind - Parameter replace (original value)'
[15:21:58] [INFO] testing 'Microsoft Access boolean-based blind - Parameter replace'
[15:21:58] [INFO] testing 'Microsoft Access boolean-based blind - Parameter replace (original value)'
[15:21:58] [INFO] testing 'Boolean-based blind - Parameter replace (DUAL)'
[15:21:58] [INFO] testing 'Boolean-based blind - Parameter replace (DUAL - original value)'
[15:21:58] [INFO] testing 'Boolean-based blind - Parameter replace (CASE)'
[15:21:58] [INFO] testing 'Boolean-based blind - Parameter replace (CASE - original value)'
[15:21:58] [INFO] testing 'MySQL >= 5.0 boolean-based blind - ORDER BY, GROUP BY clause'
[15:21:58] [INFO] testing 'MySQL >= 5.0 boolean-based blind - ORDER BY, GROUP BY clause (original value)'
[15:21:58] [INFO] testing 'MySQL < 5.0 boolean-based blind - ORDER BY, GROUP BY clause'
[15:21:58] [INFO] testing 'MySQL < 5.0 boolean-based blind - ORDER BY, GROUP BY clause (original value)'
[15:21:58] [INFO] testing 'PostgreSQL boolean-based blind - ORDER BY, GROUP BY clause'
[15:21:58] [INFO] testing 'PostgreSQL boolean-based blind - ORDER BY clause (original value)'
[15:21:58] [INFO] testing 'PostgreSQL boolean-based blind - ORDER BY clause (GENERATE_SERIES)'
[15:21:58] [INFO] testing 'Microsoft SQL Server/Sybase boolean-based blind - ORDER BY clause'
[15:21:58] [INFO] testing 'Microsoft SQL Server/Sybase boolean-based blind - ORDER BY clause (original value)'
[15:21:58] [INFO] testing 'Oracle boolean-based blind - ORDER BY, GROUP BY clause'
[15:21:58] [INFO] testing 'Oracle boolean-based blind - ORDER BY, GROUP BY clause (original value)'
[15:21:58] [INFO] testing 'Microsoft Access boolean-based blind - ORDER BY, GROUP BY clause'
[15:21:58] [INFO] testing 'Microsoft Access boolean-based blind - ORDER BY, GROUP BY clause (original value)'
[15:21:58] [INFO] testing 'SAP MaxDB boolean-based blind - ORDER BY, GROUP BY clause'
[15:21:58] [INFO] testing 'SAP MaxDB boolean-based blind - ORDER BY, GROUP BY clause (original value)'
[15:21:58] [INFO] testing 'IBM DB2 boolean-based blind - ORDER BY clause'
[15:21:58] [INFO] testing 'IBM DB2 boolean-based blind - ORDER BY clause (original value)'
[15:21:58] [INFO] testing 'HAVING boolean-based blind - WHERE, GROUP BY clause'
[15:21:58] [INFO] testing 'MySQL >= 5.0 boolean-based blind - Stacked queries'
[15:21:58] [INFO] testing 'MySQL < 5.0 boolean-based blind - Stacked queries'
[15:21:59] [INFO] testing 'PostgreSQL boolean-based blind - Stacked queries'
[15:21:59] [INFO] testing 'PostgreSQL boolean-based blind - Stacked queries (GENERATE_SERIES)'
[15:21:59] [INFO] testing 'Microsoft SQL Server/Sybase boolean-based blind - Stacked queries (IF)'
[15:21:59] [INFO] testing 'Microsoft SQL Server/Sybase boolean-based blind - Stacked queries'
[15:22:00] [INFO] testing 'Oracle boolean-based blind - Stacked queries'
[15:22:00] [INFO] testing 'Microsoft Access boolean-based blind - Stacked queries'
[15:22:00] [INFO] testing 'SAP MaxDB boolean-based blind - Stacked queries'
[15:22:00] [INFO] testing 'MySQL >= 5.5 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (BIGINT UNSIGNED)'
[15:22:01] [INFO] testing 'MySQL >= 5.5 OR error-based - WHERE or HAVING clause (BIGINT UNSIGNED)'
[15:22:01] [INFO] testing 'MySQL >= 5.5 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXP)'
[15:22:01] [INFO] testing 'MySQL >= 5.5 OR error-based - WHERE or HAVING clause (EXP)'
[15:22:01] [INFO] testing 'MySQL >= 5.6 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (GTID_SUBSET)'
[15:22:02] [INFO] testing 'MySQL >= 5.6 OR error-based - WHERE or HAVING clause (GTID_SUBSET)'
[15:22:02] [INFO] testing 'MySQL >= 5.7.8 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (JSON_KEYS)'
[15:22:02] [INFO] testing 'MySQL >= 5.7.8 OR error-based - WHERE or HAVING clause (JSON_KEYS)'
[15:22:02] [INFO] testing 'MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)'
[15:22:03] [INFO] testing 'MySQL >= 5.0 OR error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)'
[15:22:03] [INFO] testing 'MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)'
[15:22:03] [INFO] testing 'MySQL >= 5.1 OR error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)'
[15:22:03] [INFO] testing 'MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (UPDATEXML)'
[15:22:04] [INFO] testing 'MySQL >= 5.1 OR error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (UPDATEXML)'
[15:22:04] [INFO] testing 'MySQL >= 4.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)'
[15:22:04] [INFO] testing 'MySQL >= 4.1 OR error-based - WHERE or HAVING clause (FLOOR)'
[15:22:05] [INFO] testing 'MySQL OR error-based - WHERE or HAVING clause (FLOOR)'
[15:22:05] [INFO] testing 'PostgreSQL AND error-based - WHERE or HAVING clause'
[15:22:05] [INFO] testing 'PostgreSQL OR error-based - WHERE or HAVING clause'
[15:22:05] [INFO] testing 'Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (IN)'
[15:22:06] [INFO] testing 'Microsoft SQL Server/Sybase OR error-based - WHERE or HAVING clause (IN)'
[15:22:06] [INFO] testing 'Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (CONVERT)'
[15:22:06] [INFO] testing 'Microsoft SQL Server/Sybase OR error-based - WHERE or HAVING clause (CONVERT)'
[15:22:06] [INFO] testing 'Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (CONCAT)'
[15:22:07] [INFO] testing 'Microsoft SQL Server/Sybase OR error-based - WHERE or HAVING clause (CONCAT)'
[15:22:07] [INFO] testing 'Oracle AND error-based - WHERE or HAVING clause (XMLType)'
[15:22:07] [INFO] testing 'Oracle OR error-based - WHERE or HAVING clause (XMLType)'
[15:22:08] [INFO] testing 'Oracle AND error-based - WHERE or HAVING clause (UTL_INADDR.GET_HOST_ADDRESS)'
[15:22:08] [INFO] testing 'Oracle OR error-based - WHERE or HAVING clause (UTL_INADDR.GET_HOST_ADDRESS)'
[15:22:08] [INFO] testing 'Oracle AND error-based - WHERE or HAVING clause (CTXSYS.DRITHSX.SN)'
[15:22:08] [INFO] testing 'Oracle OR error-based - WHERE or HAVING clause (CTXSYS.DRITHSX.SN)'
[15:22:09] [INFO] testing 'Oracle AND error-based - WHERE or HAVING clause (DBMS_UTILITY.SQLID_TO_SQLHASH)'
[15:22:09] [INFO] testing 'Oracle OR error-based - WHERE or HAVING clause (DBMS_UTILITY.SQLID_TO_SQLHASH)'
[15:22:09] [INFO] testing 'Firebird AND error-based - WHERE or HAVING clause'
[15:22:09] [INFO] testing 'Firebird OR error-based - WHERE or HAVING clause'
[15:22:10] [INFO] testing 'MonetDB AND error-based - WHERE or HAVING clause'
[15:22:11] [INFO] testing 'MonetDB OR error-based - WHERE or HAVING clause'
[15:22:11] [INFO] testing 'Vertica AND error-based - WHERE or HAVING clause'
[15:22:11] [INFO] testing 'Vertica OR error-based - WHERE or HAVING clause'
[15:22:11] [INFO] testing 'IBM DB2 AND error-based - WHERE or HAVING clause'
[15:22:11] [INFO] testing 'IBM DB2 OR error-based - WHERE or HAVING clause'
[15:22:11] [INFO] testing 'MySQL >= 5.1 error-based - PROCEDURE ANALYSE (EXTRACTVALUE)'
[15:22:12] [INFO] testing 'MySQL >= 5.5 error-based - Parameter replace (BIGINT UNSIGNED)'
[15:22:12] [INFO] testing 'MySQL >= 5.5 error-based - Parameter replace (EXP)'
[15:22:12] [INFO] testing 'MySQL >= 5.6 error-based - Parameter replace (GTID_SUBSET)'
[15:22:12] [INFO] testing 'MySQL >= 5.7.8 error-based - Parameter replace (JSON_KEYS)'
[15:22:12] [INFO] testing 'MySQL >= 5.0 error-based - Parameter replace (FLOOR)'
[15:22:12] [INFO] testing 'MySQL >= 5.1 error-based - Parameter replace (UPDATEXML)'
[15:22:12] [INFO] testing 'MySQL >= 5.1 error-based - Parameter replace (EXTRACTVALUE)'
[15:22:12] [INFO] testing 'PostgreSQL error-based - Parameter replace'
[15:22:12] [INFO] testing 'PostgreSQL error-based - Parameter replace (GENERATE_SERIES)'
[15:22:12] [INFO] testing 'Microsoft SQL Server/Sybase error-based - Parameter replace'
[15:22:12] [INFO] testing 'Microsoft SQL Server/Sybase error-based - Parameter replace (integer column)'
[15:22:12] [INFO] testing 'Oracle error-based - Parameter replace'
[15:22:12] [INFO] testing 'Firebird error-based - Parameter replace'
[15:22:12] [INFO] testing 'IBM DB2 error-based - Parameter replace'
[15:22:12] [INFO] testing 'MySQL >= 5.5 error-based - ORDER BY, GROUP BY clause (BIGINT UNSIGNED)'
[15:22:12] [INFO] testing 'MySQL >= 5.5 error-based - ORDER BY, GROUP BY clause (EXP)'
[15:22:12] [INFO] testing 'MySQL >= 5.6 error-based - ORDER BY, GROUP BY clause (GTID_SUBSET)'
[15:22:12] [INFO] testing 'MySQL >= 5.7.8 error-based - ORDER BY, GROUP BY clause (JSON_KEYS)'
[15:22:12] [INFO] testing 'MySQL >= 5.0 error-based - ORDER BY, GROUP BY clause (FLOOR)'
[15:22:12] [INFO] testing 'MySQL >= 5.1 error-based - ORDER BY, GROUP BY clause (EXTRACTVALUE)'
[15:22:12] [INFO] testing 'MySQL >= 5.1 error-based - ORDER BY, GROUP BY clause (UPDATEXML)'
[15:22:12] [INFO] testing 'MySQL >= 4.1 error-based - ORDER BY, GROUP BY clause (FLOOR)'
[15:22:12] [INFO] testing 'PostgreSQL error-based - ORDER BY, GROUP BY clause'
[15:22:12] [INFO] testing 'PostgreSQL error-based - ORDER BY, GROUP BY clause (GENERATE_SERIES)'
[15:22:12] [INFO] testing 'Microsoft SQL Server/Sybase error-based - ORDER BY clause'
[15:22:12] [INFO] testing 'Oracle error-based - ORDER BY, GROUP BY clause'
[15:22:12] [INFO] testing 'Firebird error-based - ORDER BY clause'
[15:22:12] [INFO] testing 'IBM DB2 error-based - ORDER BY clause'
[15:22:12] [INFO] testing 'Microsoft SQL Server/Sybase error-based - Stacking (EXEC)'
[15:22:12] [INFO] testing 'Generic inline queries'
[15:22:12] [INFO] testing 'MySQL inline queries'
[15:22:12] [INFO] testing 'PostgreSQL inline queries'
[15:22:12] [INFO] testing 'Microsoft SQL Server/Sybase inline queries'
[15:22:12] [INFO] testing 'Oracle inline queries'
[15:22:12] [INFO] testing 'SQLite inline queries'
[15:22:12] [INFO] testing 'Firebird inline queries'
[15:22:12] [INFO] testing 'MySQL >= 5.0.12 stacked queries (comment)'
[15:22:12] [INFO] testing 'MySQL >= 5.0.12 stacked queries'
[15:22:12] [INFO] testing 'MySQL >= 5.0.12 stacked queries (query SLEEP - comment)'
[15:22:12] [INFO] testing 'MySQL >= 5.0.12 stacked queries (query SLEEP)'
[15:22:13] [INFO] testing 'MySQL < 5.0.12 stacked queries (BENCHMARK - comment)'
[15:22:13] [INFO] testing 'MySQL < 5.0.12 stacked queries (BENCHMARK)'
[15:22:13] [INFO] testing 'PostgreSQL > 8.1 stacked queries (comment)'
[15:22:13] [INFO] testing 'PostgreSQL > 8.1 stacked queries'
[15:22:13] [INFO] testing 'PostgreSQL stacked queries (heavy query - comment)'
[15:22:13] [INFO] testing 'PostgreSQL stacked queries (heavy query)'
[15:22:13] [INFO] testing 'PostgreSQL < 8.2 stacked queries (Glibc - comment)'
[15:22:14] [INFO] testing 'PostgreSQL < 8.2 stacked queries (Glibc)'
[15:22:14] [INFO] testing 'Microsoft SQL Server/Sybase stacked queries (comment)'
[15:22:14] [INFO] testing 'Microsoft SQL Server/Sybase stacked queries (DECLARE - comment)'
[15:22:14] [INFO] testing 'Microsoft SQL Server/Sybase stacked queries'
[15:22:14] [INFO] testing 'Microsoft SQL Server/Sybase stacked queries (DECLARE)'
[15:22:14] [INFO] testing 'Oracle stacked queries (DBMS_PIPE.RECEIVE_MESSAGE - comment)'
[15:22:14] [INFO] testing 'Oracle stacked queries (DBMS_PIPE.RECEIVE_MESSAGE)'
[15:22:15] [INFO] testing 'Oracle stacked queries (heavy query - comment)'
[15:22:15] [INFO] testing 'Oracle stacked queries (heavy query)'
[15:22:15] [INFO] testing 'Oracle stacked queries (DBMS_LOCK.SLEEP - comment)'
[15:22:15] [INFO] testing 'Oracle stacked queries (DBMS_LOCK.SLEEP)'
[15:22:15] [INFO] testing 'Oracle stacked queries (USER_LOCK.SLEEP - comment)'
[15:22:15] [INFO] testing 'Oracle stacked queries (USER_LOCK.SLEEP)'
[15:22:15] [INFO] testing 'IBM DB2 stacked queries (heavy query - comment)'
[15:22:15] [INFO] testing 'IBM DB2 stacked queries (heavy query)'
[15:22:15] [INFO] testing 'SQLite > 2.0 stacked queries (heavy query - comment)'
[15:22:15] [INFO] testing 'SQLite > 2.0 stacked queries (heavy query)'
[15:22:16] [INFO] testing 'Firebird stacked queries (heavy query - comment)'
[15:22:16] [INFO] testing 'Firebird stacked queries (heavy query)'
[15:22:16] [INFO] testing 'SAP MaxDB stacked queries (heavy query - comment)'
[15:22:16] [INFO] testing 'SAP MaxDB stacked queries (heavy query)'
[15:22:16] [INFO] testing 'HSQLDB >= 1.7.2 stacked queries (heavy query - comment)'
[15:22:16] [INFO] testing 'HSQLDB >= 1.7.2 stacked queries (heavy query)'
[15:22:17] [INFO] testing 'HSQLDB >= 2.0 stacked queries (heavy query - comment)'
[15:22:17] [INFO] testing 'HSQLDB >= 2.0 stacked queries (heavy query)'
[15:22:17] [INFO] testing 'MySQL >= 5.0.12 AND time-based blind (query SLEEP)'
[15:22:17] [INFO] testing 'MySQL >= 5.0.12 OR time-based blind (query SLEEP)'
[15:22:17] [INFO] testing 'MySQL >= 5.0.12 AND time-based blind (SLEEP)'
[15:22:18] [INFO] testing 'MySQL >= 5.0.12 OR time-based blind (SLEEP)'
[15:22:18] [INFO] testing 'MySQL >= 5.0.12 AND time-based blind (SLEEP - comment)'
[15:22:18] [INFO] testing 'MySQL >= 5.0.12 OR time-based blind (SLEEP - comment)'
[15:22:18] [INFO] testing 'MySQL >= 5.0.12 AND time-based blind (query SLEEP - comment)'
[15:22:18] [INFO] testing 'MySQL >= 5.0.12 OR time-based blind (query SLEEP - comment)'
[15:22:19] [INFO] testing 'MySQL < 5.0.12 AND time-based blind (BENCHMARK)'
[15:22:19] [INFO] testing 'MySQL > 5.0.12 AND time-based blind (heavy query)'
[15:22:19] [INFO] testing 'MySQL < 5.0.12 OR time-based blind (BENCHMARK)'
[15:22:19] [INFO] testing 'MySQL > 5.0.12 OR time-based blind (heavy query)'
[15:22:20] [INFO] testing 'MySQL < 5.0.12 AND time-based blind (BENCHMARK - comment)'
[15:22:20] [INFO] testing 'MySQL > 5.0.12 AND time-based blind (heavy query - comment)'
[15:22:20] [INFO] testing 'MySQL < 5.0.12 OR time-based blind (BENCHMARK - comment)'
[15:22:20] [INFO] testing 'MySQL > 5.0.12 OR time-based blind (heavy query - comment)'
[15:22:20] [INFO] testing 'MySQL >= 5.0.12 RLIKE time-based blind'
[15:22:20] [INFO] testing 'MySQL >= 5.0.12 RLIKE time-based blind (comment)'
[15:22:20] [INFO] testing 'MySQL >= 5.0.12 RLIKE time-based blind (query SLEEP)'
[15:22:21] [INFO] testing 'MySQL >= 5.0.12 RLIKE time-based blind (query SLEEP - comment)'
[15:22:21] [INFO] testing 'MySQL AND time-based blind (ELT)'
[15:22:21] [INFO] testing 'MySQL OR time-based blind (ELT)'
[15:22:21] [INFO] testing 'MySQL AND time-based blind (ELT - comment)'
[15:22:21] [INFO] testing 'MySQL OR time-based blind (ELT - comment)'
[15:22:22] [INFO] testing 'PostgreSQL > 8.1 AND time-based blind'
[15:22:22] [INFO] testing 'PostgreSQL > 8.1 OR time-based blind'
[15:22:22] [INFO] testing 'PostgreSQL > 8.1 AND time-based blind (comment)'
[15:22:22] [INFO] testing 'PostgreSQL > 8.1 OR time-based blind (comment)'
[15:22:22] [INFO] testing 'PostgreSQL AND time-based blind (heavy query)'
[15:22:22] [INFO] testing 'PostgreSQL OR time-based blind (heavy query)'
[15:22:23] [INFO] testing 'PostgreSQL AND time-based blind (heavy query - comment)'
[15:22:23] [INFO] testing 'PostgreSQL OR time-based blind (heavy query - comment)'
[15:22:23] [INFO] testing 'Microsoft SQL Server/Sybase time-based blind (IF)'
[15:22:23] [INFO] testing 'Microsoft SQL Server/Sybase time-based blind (IF - comment)'
[15:22:23] [INFO] testing 'Microsoft SQL Server/Sybase AND time-based blind (heavy query)'
[15:22:24] [INFO] testing 'Microsoft SQL Server/Sybase OR time-based blind (heavy query)'
[15:22:24] [INFO] testing 'Microsoft SQL Server/Sybase AND time-based blind (heavy query - comment)'
[15:22:24] [INFO] testing 'Microsoft SQL Server/Sybase OR time-based blind (heavy query - comment)'
[15:22:24] [INFO] testing 'Oracle AND time-based blind'
[15:22:24] [INFO] testing 'Oracle OR time-based blind'
[15:22:25] [INFO] testing 'Oracle AND time-based blind (comment)'
[15:22:25] [INFO] testing 'Oracle OR time-based blind (comment)'
[15:22:25] [INFO] testing 'Oracle AND time-based blind (heavy query)'
[15:22:25] [INFO] testing 'Oracle OR time-based blind (heavy query)'
[15:22:25] [INFO] testing 'Oracle AND time-based blind (heavy query - comment)'
[15:22:26] [INFO] testing 'Oracle OR time-based blind (heavy query - comment)'
[15:22:26] [INFO] testing 'IBM DB2 AND time-based blind (heavy query)'
[15:22:26] [INFO] testing 'IBM DB2 OR time-based blind (heavy query)'
[15:22:26] [INFO] testing 'IBM DB2 AND time-based blind (heavy query - comment)'
[15:22:26] [INFO] testing 'IBM DB2 OR time-based blind (heavy query - comment)'
[15:22:26] [INFO] testing 'SQLite > 2.0 AND time-based blind (heavy query)'
[15:22:26] [INFO] testing 'SQLite > 2.0 OR time-based blind (heavy query)'
[15:22:27] [INFO] testing 'SQLite > 2.0 AND time-based blind (heavy query - comment)'
[15:22:27] [INFO] testing 'SQLite > 2.0 OR time-based blind (heavy query - comment)'
[15:22:27] [INFO] testing 'Firebird >= 2.0 AND time-based blind (heavy query)'
[15:22:27] [INFO] testing 'Firebird >= 2.0 OR time-based blind (heavy query)'
[15:22:27] [INFO] testing 'Firebird >= 2.0 AND time-based blind (heavy query - comment)'
[15:22:28] [INFO] testing 'Firebird >= 2.0 OR time-based blind (heavy query - comment)'
[15:22:28] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query)'
[15:22:28] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query)'
[15:22:28] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query - comment)'
[15:22:28] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query - comment)'
[15:22:29] [INFO] testing 'HSQLDB >= 1.7.2 AND time-based blind (heavy query)'
[15:22:29] [INFO] testing 'HSQLDB >= 1.7.2 OR time-based blind (heavy query)'
[15:22:29] [INFO] testing 'HSQLDB >= 1.7.2 AND time-based blind (heavy query - comment)'
[15:22:29] [INFO] testing 'HSQLDB >= 1.7.2 OR time-based blind (heavy query - comment)'
[15:22:29] [INFO] testing 'HSQLDB > 2.0 AND time-based blind (heavy query)'
[15:22:30] [INFO] testing 'HSQLDB > 2.0 OR time-based blind (heavy query)'
[15:22:30] [INFO] testing 'HSQLDB > 2.0 AND time-based blind (heavy query - comment)'
[15:22:30] [INFO] testing 'HSQLDB > 2.0 OR time-based blind (heavy query - comment)'
[15:22:30] [INFO] testing 'Informix AND time-based blind (heavy query)'
[15:22:30] [INFO] testing 'Informix OR time-based blind (heavy query)'
[15:22:30] [INFO] testing 'Informix AND time-based blind (heavy query - comment)'
[15:22:31] [INFO] testing 'Informix OR time-based blind (heavy query - comment)'
[15:22:31] [INFO] testing 'MySQL >= 5.1 time-based blind (heavy query) - PROCEDURE ANALYSE (EXTRACTVALUE)'
[15:22:31] [INFO] testing 'MySQL >= 5.1 time-based blind (heavy query - comment) - PROCEDURE ANALYSE (EXTRACTVALUE)'
[15:22:31] [INFO] testing 'MySQL >= 5.0.12 time-based blind - Parameter replace'
[15:22:31] [INFO] testing 'MySQL >= 5.0.12 time-based blind - Parameter replace (substraction)'
[15:22:31] [INFO] testing 'MySQL < 5.0.12 time-based blind - Parameter replace (BENCHMARK)'
[15:22:31] [INFO] testing 'MySQL > 5.0.12 time-based blind - Parameter replace (heavy query - comment)'
[15:22:31] [INFO] testing 'MySQL time-based blind - Parameter replace (bool)'
[15:22:31] [INFO] testing 'MySQL time-based blind - Parameter replace (ELT)'
[15:22:31] [INFO] testing 'MySQL time-based blind - Parameter replace (MAKE_SET)'
[15:22:31] [INFO] testing 'PostgreSQL > 8.1 time-based blind - Parameter replace'
[15:22:31] [INFO] testing 'PostgreSQL time-based blind - Parameter replace (heavy query)'
[15:22:31] [INFO] testing 'Microsoft SQL Server/Sybase time-based blind - Parameter replace (heavy queries)'
[15:22:31] [INFO] testing 'Oracle time-based blind - Parameter replace (DBMS_LOCK.SLEEP)'
[15:22:31] [INFO] testing 'Oracle time-based blind - Parameter replace (DBMS_PIPE.RECEIVE_MESSAGE)'
[15:22:31] [INFO] testing 'Oracle time-based blind - Parameter replace (heavy queries)'
[15:22:31] [INFO] testing 'SQLite > 2.0 time-based blind - Parameter replace (heavy query)'
[15:22:31] [INFO] testing 'Firebird time-based blind - Parameter replace (heavy query)'
[15:22:31] [INFO] testing 'SAP MaxDB time-based blind - Parameter replace (heavy query)'
[15:22:31] [INFO] testing 'IBM DB2 time-based blind - Parameter replace (heavy query)'
[15:22:31] [INFO] testing 'HSQLDB >= 1.7.2 time-based blind - Parameter replace (heavy query)'
[15:22:32] [INFO] testing 'HSQLDB > 2.0 time-based blind - Parameter replace (heavy query)'
[15:22:32] [INFO] testing 'Informix time-based blind - Parameter replace (heavy query)'
[15:22:32] [INFO] testing 'MySQL >= 5.0.12 time-based blind - ORDER BY, GROUP BY clause'
[15:22:32] [INFO] testing 'MySQL < 5.0.12 time-based blind - ORDER BY, GROUP BY clause (BENCHMARK)'
[15:22:32] [INFO] testing 'PostgreSQL > 8.1 time-based blind - ORDER BY, GROUP BY clause'
[15:22:32] [INFO] testing 'PostgreSQL time-based blind - ORDER BY, GROUP BY clause (heavy query)'
[15:22:32] [INFO] testing 'Microsoft SQL Server/Sybase time-based blind - ORDER BY clause (heavy query)'
[15:22:32] [INFO] testing 'Oracle time-based blind - ORDER BY, GROUP BY clause (DBMS_LOCK.SLEEP)'
[15:22:32] [INFO] testing 'Oracle time-based blind - ORDER BY, GROUP BY clause (DBMS_PIPE.RECEIVE_MESSAGE)'
[15:22:32] [INFO] testing 'Oracle time-based blind - ORDER BY, GROUP BY clause (heavy query)'
[15:22:32] [INFO] testing 'HSQLDB >= 1.7.2 time-based blind - ORDER BY, GROUP BY clause (heavy query)'
[15:22:32] [INFO] testing 'HSQLDB > 2.0 time-based blind - ORDER BY, GROUP BY clause (heavy query)'
it is recommended to perform only basic UNION tests if there is not at least one other (potential) technique found. Do you want to reduce the number of requests? [Y/n] n
[15:29:07] [INFO] testing 'Generic UNION query (NULL) - 1 to 10 columns'
[15:29:09] [WARNING] user aborted during detection phase
how do you want to proceed? [(S)kip current test/(e)nd detection phase/(n)ext parameter/(c)hange verbosity/(q)uit]
[15:29:10] [WARNING] HTTP error codes detected during run:
408 (Request Timeout) - 1 times
[15:29:10] [ERROR] user quit
[15:29:10] [WARNING] your sqlmap version is outdated

[*] ending @ 15:29:10 /2025-03-08/
sergio@Sergio:~$ sqlmap -u "http://localhost:4000/api/transfer?id=67cc8dd49701af77c7497427" --risk=3 --level=5
        ___
       __H__
 ___ ___["]_____ ___ ___  {1.6.4#stable}
|_ -| . [,]     | .'| . |
|___|_  [(]_|_|_|__,|  _|
      |_|V...       |_|   https://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 15:29:44 /2025-03-08/

[15:29:44] [INFO] testing connection to the target URL
[15:29:44] [INFO] testing if the target URL content is stable
[15:29:44] [WARNING] target URL content is not stable (i.e. content differs). sqlmap will base the page comparison on a sequence matcher. If no dynamic nor injectable parameters are detected, or in case of junk results, refer to user's manual paragraph 'Page comparison'
how do you want to proceed? [(C)ontinue/(s)tring/(r)egex/(q)uit] c
[15:29:51] [INFO] testing if GET parameter 'id' is dynamic
[15:29:51] [INFO] GET parameter 'id' appears to be dynamic
[15:29:51] [WARNING] heuristic (basic) test shows that GET parameter 'id' might not be injectable
[15:29:51] [INFO] testing for SQL injection on GET parameter 'id'
[15:29:51] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause'
[15:29:52] [INFO] GET parameter 'id' appears to be 'AND boolean-based blind - WHERE or HAVING clause' injectable
[15:29:52] [INFO] heuristic (extended) test shows that the back-end DBMS could be 'SAP MaxDB'
it looks like the back-end DBMS is 'SAP MaxDB'. Do you want to skip test payloads specific for other DBMSes? [Y/n] y
[15:29:56] [INFO] testing 'Generic inline queries'
[15:29:56] [INFO] testing 'SAP MaxDB stacked queries (heavy query - comment)'
[15:29:56] [WARNING] time-based comparison requires larger statistical model, please wait.... (done)
[15:29:56] [INFO] testing 'SAP MaxDB stacked queries (heavy query)'
[15:29:56] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query)'
[15:29:56] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query)'
[15:29:56] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query - comment)'
[15:29:56] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query - comment)'
[15:29:56] [INFO] testing 'SAP MaxDB time-based blind - Parameter replace (heavy query)'
[15:29:56] [INFO] testing 'Generic UNION query (NULL) - 1 to 20 columns'
[15:29:56] [INFO] automatically extending ranges for UNION query injection technique tests as there is at least one other (potential) technique found
[15:29:56] [INFO] testing 'Generic UNION query (random number) - 1 to 20 columns'
[15:29:56] [INFO] testing 'Generic UNION query (NULL) - 21 to 40 columns'
[15:29:56] [INFO] testing 'Generic UNION query (random number) - 21 to 40 columns'
[15:29:56] [INFO] testing 'Generic UNION query (NULL) - 41 to 60 columns'
[15:29:56] [INFO] testing 'Generic UNION query (random number) - 41 to 60 columns'
[15:29:56] [INFO] testing 'Generic UNION query (NULL) - 61 to 80 columns'
[15:29:57] [INFO] testing 'Generic UNION query (random number) - 61 to 80 columns'
[15:29:57] [INFO] testing 'Generic UNION query (NULL) - 81 to 100 columns'
[15:29:57] [INFO] testing 'Generic UNION query (random number) - 81 to 100 columns'
[15:29:57] [INFO] checking if the injection point on GET parameter 'id' is a false positive
[15:29:57] [WARNING] false positive or unexploitable injection point detected
[15:29:57] [WARNING] GET parameter 'id' does not seem to be injectable
[15:29:57] [INFO] testing if parameter 'User-Agent' is dynamic
[15:29:57] [INFO] parameter 'User-Agent' appears to be dynamic
[15:29:57] [WARNING] heuristic (basic) test shows that parameter 'User-Agent' might not be injectable
[15:29:57] [INFO] testing for SQL injection on parameter 'User-Agent'
[15:29:57] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause'
[15:29:57] [INFO] parameter 'User-Agent' appears to be 'AND boolean-based blind - WHERE or HAVING clause' injectable
[15:29:57] [INFO] testing 'Generic inline queries'
[15:29:57] [INFO] testing 'SAP MaxDB stacked queries (heavy query - comment)'
[15:29:57] [INFO] testing 'SAP MaxDB stacked queries (heavy query)'
[15:29:57] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query)'
[15:29:57] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query)'
[15:29:57] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query - comment)'
[15:29:57] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query - comment)'
[15:29:57] [INFO] testing 'SAP MaxDB time-based blind - Parameter replace (heavy query)'
[15:29:57] [INFO] testing 'Generic UNION query (NULL) - 1 to 20 columns'
[15:29:57] [INFO] testing 'Generic UNION query (random number) - 1 to 20 columns'
[15:29:57] [INFO] testing 'Generic UNION query (NULL) - 21 to 40 columns'
[15:29:57] [INFO] testing 'Generic UNION query (random number) - 21 to 40 columns'
[15:29:57] [INFO] testing 'Generic UNION query (NULL) - 41 to 60 columns'
[15:29:57] [INFO] testing 'Generic UNION query (random number) - 41 to 60 columns'
[15:29:58] [INFO] testing 'Generic UNION query (NULL) - 61 to 80 columns'
[15:29:58] [INFO] testing 'Generic UNION query (random number) - 61 to 80 columns'
[15:29:58] [INFO] testing 'Generic UNION query (NULL) - 81 to 100 columns'
[15:29:58] [INFO] testing 'Generic UNION query (random number) - 81 to 100 columns'
[15:29:58] [INFO] checking if the injection point on User-Agent parameter 'User-Agent' is a false positive
[15:29:58] [WARNING] false positive or unexploitable injection point detected
[15:29:58] [WARNING] parameter 'User-Agent' does not seem to be injectable
[15:29:58] [INFO] testing if parameter 'Referer' is dynamic
[15:29:58] [INFO] parameter 'Referer' appears to be dynamic
[15:29:58] [WARNING] heuristic (basic) test shows that parameter 'Referer' might not be injectable
[15:29:58] [INFO] testing for SQL injection on parameter 'Referer'
[15:29:58] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause'
[15:29:58] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause'
[15:29:59] [INFO] parameter 'Referer' appears to be 'OR boolean-based blind - WHERE or HAVING clause' injectable
[15:29:59] [INFO] testing 'Generic inline queries'
[15:29:59] [INFO] testing 'SAP MaxDB stacked queries (heavy query - comment)'
[15:29:59] [INFO] testing 'SAP MaxDB stacked queries (heavy query)'
[15:29:59] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query)'
[15:29:59] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query)'
[15:29:59] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query - comment)'
[15:29:59] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query - comment)'
[15:29:59] [INFO] testing 'SAP MaxDB time-based blind - Parameter replace (heavy query)'
[15:29:59] [INFO] testing 'Generic UNION query (NULL) - 1 to 20 columns'
[15:29:59] [INFO] testing 'Generic UNION query (random number) - 1 to 20 columns'
[15:29:59] [INFO] testing 'Generic UNION query (NULL) - 21 to 40 columns'
[15:29:59] [INFO] testing 'Generic UNION query (random number) - 21 to 40 columns'
[15:29:59] [INFO] testing 'Generic UNION query (NULL) - 41 to 60 columns'
[15:29:59] [INFO] testing 'Generic UNION query (random number) - 41 to 60 columns'
[15:29:59] [INFO] testing 'Generic UNION query (NULL) - 61 to 80 columns'
[15:29:59] [INFO] testing 'Generic UNION query (random number) - 61 to 80 columns'
[15:29:59] [INFO] testing 'Generic UNION query (NULL) - 81 to 100 columns'
[15:30:00] [INFO] testing 'Generic UNION query (random number) - 81 to 100 columns'
[15:30:00] [WARNING] in OR boolean-based injection cases, please consider usage of switch '--drop-set-cookie' if you experience any problems during data retrieval
[15:30:00] [INFO] checking if the injection point on Referer parameter 'Referer' is a false positive
[15:30:00] [WARNING] false positive or unexploitable injection point detected
[15:30:00] [WARNING] parameter 'Referer' does not seem to be injectable
[15:30:00] [INFO] testing if parameter 'Host' is dynamic
[15:30:00] [WARNING] parameter 'Host' does not appear to be dynamic
[15:30:00] [WARNING] heuristic (basic) test shows that parameter 'Host' might not be injectable
[15:30:00] [INFO] testing for SQL injection on parameter 'Host'
[15:30:00] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause'
[15:30:00] [INFO] testing 'OR boolean-based blind - WHERE or HAVING clause'
[15:30:01] [INFO] parameter 'Host' appears to be 'OR boolean-based blind - WHERE or HAVING clause' injectable
[15:30:01] [INFO] testing 'Generic inline queries'
[15:30:01] [INFO] testing 'SAP MaxDB stacked queries (heavy query - comment)'
[15:30:01] [INFO] testing 'SAP MaxDB stacked queries (heavy query)'
[15:30:01] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query)'
[15:30:01] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query)'
[15:30:01] [INFO] testing 'SAP MaxDB AND time-based blind (heavy query - comment)'
[15:30:01] [INFO] testing 'SAP MaxDB OR time-based blind (heavy query - comment)'
[15:30:01] [INFO] testing 'SAP MaxDB time-based blind - Parameter replace (heavy query)'
[15:30:01] [INFO] testing 'Generic UNION query (NULL) - 1 to 20 columns'
[15:30:01] [INFO] testing 'Generic UNION query (random number) - 1 to 20 columns'
[15:30:01] [INFO] testing 'Generic UNION query (NULL) - 21 to 40 columns'
[15:30:01] [INFO] testing 'Generic UNION query (random number) - 21 to 40 columns'
[15:30:01] [INFO] testing 'Generic UNION query (NULL) - 41 to 60 columns'
[15:30:01] [INFO] testing 'Generic UNION query (random number) - 41 to 60 columns'
[15:30:01] [INFO] testing 'Generic UNION query (NULL) - 61 to 80 columns'
[15:30:01] [INFO] testing 'Generic UNION query (random number) - 61 to 80 columns'
[15:30:01] [INFO] testing 'Generic UNION query (NULL) - 81 to 100 columns'
[15:30:01] [INFO] testing 'Generic UNION query (random number) - 81 to 100 columns'
[15:30:02] [WARNING] in OR boolean-based injection cases, please consider usage of switch '--drop-set-cookie' if you experience any problems during data retrieval
[15:30:02] [INFO] checking if the injection point on Host parameter 'Host' is a false positive
[15:30:02] [WARNING] false positive or unexploitable injection point detected
[15:30:02] [WARNING] parameter 'Host' does not seem to be injectable
[15:30:02] [CRITICAL] all tested parameters do not appear to be injectable. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') and/or switch '--random-agent'
[15:30:02] [WARNING] your sqlmap version is outdated

[*] ending @ 15:30:02 /2025-03-08/

sergio@Sergio:~$
